version: "3"

services:
  nginx:
    container_name: nginx
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src/public:/usr/share/nginx/html
    depends_on:
      - php
  php:
    container_name: php
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html/src
    depends_on:
      - db

  db:
    platform: linux/x86_64
    container_name: db
    image: mysql:8.0
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./docker/mysql/my.conf:/etc/mysql/conf.d/my.conf
    environment:
      MYSQL_DATABASE: push_notification
      MYSQL_ROOT_PASSWORD: root
      TZ: 'Asia/Tokyo'
